### ISSUE TITLE
Kuro is not working

### ISSUE THREAD

**Issue by 9MoIssam9** [deceptions/no#107]
- Android version 11
 - App version 1.9.0 beta / I also tried 1.8.5
 - Phone model Samsung M51

![Screenshot_20220127-193056_Kuro Beta](https://user-images.githubusercontent.com/98220178/151412838-d270658a-42f8-4710-9993-7c53ce7273b6.png)

**Comment by deceptions** [comment]
It is likely an ISP issue as it works on my device. Does it work with a VPN?

**Comment by 9MoIssam9** [comment]
Kuro works after I select NONE for this option (DNS after Https).Thanks Bro
