### ISSUE TITLE
search history

### ISSUE THREAD

**Issue by Redddtt** [deceptions/no#108]
You cant interact with the search history if you search an anime>go to an anime page> go back and delete your search> see error

1. search an anime
2. Click on an anime page
3. go back then delete what you searched

https://drive.google.com/file/d/1uQHloEINbIAL-njQigsePXLKyp2X-GFu/view?usp=sharing

 - Android 11
 - beta 1.9.0
 - RMX3081
 
 My reports are back

**Comment by deceptions** [comment]
Next update :+1:
