### ISSUE TITLE
Unreleased Anime

### ISSUE THREAD

**Issue by Redddtt** [deceptions/no#109]
Going to an unreleased anime should have no episodes

1. Go to an anime thats unreleased
2. See error

https://drive.google.com/file/d/1uQh3VNYItvmRrmb9F578mr-QVIuLY05z/view?usp=sharing

 - Android 11
 - beta 1.9.0
 - RMX3081

**Additional context**
Reported this since it might confuse some peps

**Comment by deceptions** [comment]
Fixed next update
Thank you for the reports :heart:
