### ISSUE TITLE
Batch download

### ISSUE THREAD

**Issue by Redddtt** [deceptions/no#113]
Batch download downloads the next first ep on another episode group

1. batch download an anime that has 21+ eps
2. See error

https://drive.google.com/file/d/1yVLpZT26EP8ssn-THsKRav034MOLkX16/view?usp=sharing

 - Android 11
 - beta 1.9.0
 - recorded on an emulator, same error on RMX3081

**Comment by deceptions** [comment]
Fixed next update :+1:
