### ISSUE TITLE
Anime on continue watching disappear if I reopen the app

### ISSUE THREAD

**Issue by Adi-MayNotSpeak** [deceptions/no#116]
The anime diseappears if I close and open the app , I have to open the search , setting or list to get them back

**Comment by Redddtt** [comment]
In the tv app?

**Comment by Adi-MayNotSpeak** [comment]
> In the tv app?

Yeah

**Comment by Blatzar** [comment]
![image](https://user-images.githubusercontent.com/46196380/151779068-f34c9199-e112-4716-b6bc-9791ff1a775e.png)
You on the beta or no?

**Comment by Redddtt** [comment]
> The anime diseappears if I close and open the app , I have to open the search , setting or list to get them back 
> 
> 

I think he was referring to this error
↓
https://drive.google.com/file/d/1vudR3DEMNf49kUDQUKoMeOijyEaABkth/view?usp=drivesdk

Beta 1.9.0
Sony Bravia ur3

**Comment by Adi-MayNotSpeak** [comment]
> ![image](https://user-images.githubusercontent.com/46196380/151779068-f34c9199-e112-4716-b6bc-9791ff1a775e.png) You on the beta or no?

I am on the beta version

**Comment by Adi-MayNotSpeak** [comment]
> > The anime diseappears if I close and open the app , I have to open the search , setting or list to get them back
> 
> I think he was referring to this error ↓ https://drive.google.com/file/d/1vudR3DEMNf49kUDQUKoMeOijyEaABkth/view?usp=drivesdk
> 
> Beta 1.9.0 Sony Bravia ur3

Yeah 👍

**Comment by deceptions** [comment]
Continue watching is loaded separately which means it might take some extra time if there is a lot of items. Does it load if you just wait a while?

**Comment by Redddtt** [comment]
> Continue watching is loaded separately which means it might take some extra time if there is a lot of items. 

Does it load if you just wait a while?
No. fixed if i go to any type of page and if i scroll down then up it is partially fixed

**Comment by Adi-MayNotSpeak** [comment]
> ![image](https://user-images.githubusercontent.com/46196380/151779068-f34c9199-e112-4716-b6bc-9791ff1a775e.png) You on the beta or no?

Wait a minute , aren't you thr original developer of this app , and you are currently working on cloudstream ?

**Comment by Blatzar** [comment]
Yes? :raised_eyebrow:

**Comment by Adi-MayNotSpeak** [comment]
> Yes? 🤨

Bruh for such a great developer to be aware of my favourite app 🛐 , have you considered working with deceptions on this one ?

**Comment by Adi-MayNotSpeak** [comment]
> > Continue watching is loaded separately which means it might take some extra time if there is a lot of items.
> 
> Does it load if you just wait a while? No. fixed if i go to any type of page and if i scroll down then up it is partially fixed

Well , the refresh button fixed this so I am closing it (for some reason deceptions doesn't close issues)
