### ISSUE TITLE
How much wait for the new source

### ISSUE THREAD

**Issue by Adi-MayNotSpeak** [deceptions/no#119]
It's been so long since you announced , plz do it fast , it's the only thing lacking in your app , if you add some better sources ISTG the will become just netflix

**Comment by Redddtt** [comment]
deceptions said that he wants a bug free app before adding a new site (idk if thats still the plan). If you guys are gonna report bugs please follow the bug template to keep questions to its minimum. You can join Kuro s community/discord server to ask for more info and help

**Comment by Adi-MayNotSpeak** [comment]
> deceptions said that he wants a bug free app before adding a new site (idk if thats still the plan). If you guys are gonna report bugs please follow the bug template to keep questions to its minimum. You can join Kuro s community/discord server to ask for more info and help

Yeah but watching naruto is difficult sometimes (quality on some eps is 360p)
