### ISSUE TITLE
Imma announce a source and then won't act on it a a single time

### ISSUE THREAD

**Issue by Adi-MayNotSpeak** [deceptions/no#123]
🤡

**Comment by Adi-MayNotSpeak** [comment]
> 🤡

I am sorry that I am being toxic but I am literally so pissed , the only app that works for me is not adding the one feature due to which I am not able to use this app , this is a once in a lifetime request , please add some better source 😢 (sakura reference)

**Comment by deceptions** [comment]
We were planning another source in 2021 but since Red found so many bugs we focused on stability instead. 

Now we are actually halfway through adding another site but this issue has convinced me to postpone it even more and focus more on the UI in the next update :+1: 

Patience is a virtue.

**Comment by Adi-MayNotSpeak** [comment]
> We were planning another source in 2021 but since Red found so many bugs we focused on stability instead.
> 
> Now we are actually halfway through adding another site but this issue has convinced me to postpone it even more and focus more on the UI in the next update 👍
> 
> Patience is a virtue.

I understand, this is the only app that works for me , Is adding new sources that difficult ?, sorry I am not a developer
