### ISSUE TITLE
Subscribe on TV version

### ISSUE THREAD

**Issue by jeyjai** [deceptions/no#129]
Quick question on subscribe for the tv version.
I know notifications on android tv might be problematic but how does this work?
Let's say my app is closed when the episode notifications is supposed to go out, will it notify me next time i open the app instead? And if not, would it be possible to have it work this way as a kind of backup even on phones if the app is killed or closed before the check?

Because i have subscribe on for two shows on my tv and still not getting any notifications

**Comment by deceptions** [comment]
Subscribing works by fetching the series in the background every X hours. This feature uses Workmanager which works even if you closed the app in the overview screen but not if you killed the app. Regardless this feature will be removed in future Kuro TV versions and is not intended to work in the current one.
