### ISSUE TITLE
Downloads are super slow

### ISSUE THREAD

**Issue by Salamanka1212** [deceptions/no#13]
Am i the only one that has slow download speed? Again its not my wifi because when im downloading normally on chrome it fast not like in the app. I even tried to download 1 at a time but its still slow.

**To Reproduce**
1. Go to any anime
2. Click on download in 1080p
3. See error/bug

 - android 11
 - 1.2.1
 - Realme8pro

**Additional context**
Just want to make sure if this is an app problem or just me

**Comment by deceptions** [comment]
I am not getting much faster speeds than on chrome. Their servers are just slow. Use the manual download picker to pick other servers if available.
