### ISSUE TITLE
Error loading anime page

### ISSUE THREAD

**Issue by jeybsss** [deceptions/no#13]
"error loading anime page" always pops up every time i press an anime in the library section (mal) few animes that don't have this bug is one piece and bleach, and the rest is the error.

oppo f3
android 7.0
no 1.0.3

**Comment by deceptions** [comment]
I am well aware. That is because the recommendations are fetched from Anilist and not gogoanime. The system for fetching anime pages from Anilist/MAL ID:s is not good currently and can not get perfect, but I will try to improve it.

**Comment by ty-coon** [comment]
> "error loading anime page" always pops up every time i press an anime in the library section (mal) few animes that don't have this bug is one piece and bleach, and the rest is the error.
> 
> oppo f3
> android 7.0
> no 1.0.3

There's a method for it, set slugs, if u don't know how to set it, i have a video for reference.

**Comment by jeybsss** [comment]
well yeah i tried doing that but i actually don't know how to, can you please show me the vid so i can set it?

**Comment by ty-coon** [comment]
> well yeah i tried doing that but i actually don't know how to, can you please show me the vid so i can set it?

https://streamtape.com/v/kZmxmye8QySOMZk/Screenrecording_20210919_185347.mp4

By chance if its wrong syncing in mal/anilist u can set slugs for it too

**Comment by ty-coon** [comment]
https://streamtape.com/v/qJyBoBwl4XsRBd/Screenrecording_20210811_233313.mp4
 A better example

**Comment by deceptions** [comment]
Fixed in 1.1.1.
I can not improve the MAL/Anilist linking beyond the current implementation.
