### ISSUE TITLE
Mi A3 Status bar not visible...

### ISSUE THREAD

**Issue by sandeepdokala** [deceptions/no#138]
Status bar not visible not visible on Mi A3 when running the app

![Screenshot_20220305-171714_Kuro.png](https://user-images.githubusercontent.com/26852582/156881634-49fd406e-7d95-4ebb-bd29-bf12ce52aa7e.png)

 - Android 11, 12 - Tested on all these
 - 1.9.3 and lower
 - Xiaomi A3 or Mi A3

**Comment by Redddtt** [comment]
Turn off hide status bar in the style settings

**Comment by sandeepdokala** [comment]
Didn't notice, sorry
