### ISSUE TITLE
The bar thing on info page - bug

### ISSUE THREAD

**Issue by Salamanka1212** [deceptions/no#14]
The bar thing on info page goes up when i watched an anime

**To Reproduce**
1. Go to anime info
2. Watch episode
3. Go back

https://drive.google.com/file/d/1CLH4SIIsF_sn6odXcYbYOhfbKFOUnUfS/view?usp=drivesdk

 -11
 - 1.2.1
 - Realme8pro

**Comment by singh043** [comment]
![Screenshot_2021-10-04-22-43-08-760_com deceptions no](https://user-images.githubusercontent.com/90082683/135894784-426f9fbf-202c-4374-988a-425a81f32b9a.jpg)
Im also having this issue see the bar on detective conon continue pic

**Comment by deceptions** [comment]
Unsure how to fix or replicate, but I will double check the code. Thank you for the video :smile:

**Comment by Salamanka1212** [comment]
Fixed, im red
