### ISSUE TITLE
sync is showing different anime

### ISSUE THREAD

**Issue by singh043** [deceptions/no#15]
For now i m hving this error only on mieruko chan anime
![IMG_20211004_224913](https://user-images.githubusercontent.com/90082683/135895660-42cb9fcb-f90e-4b3b-b620-9d5290f61d71.jpg)
![IMG_20211004_224833](https://user-images.githubusercontent.com/90082683/135895665-2ff1a26a-5bff-40db-a05a-80ca1d7cb701.jpg)
On anime info page when i try to sync using left swipe its showing different anime
![IMG_20211004_224854](https://user-images.githubusercontent.com/90082683/135895726-16999b2c-641e-470b-97fa-c5ee594c6b23.jpg)
And when i click from sync tab its showing the below error

**Comment by Salamanka1212** [comment]
U can fix the error loading anime page https://drive.google.com/file/d/1CcuWinkzQ3nJyC04dxY78i5mbmakr63B/view?usp=drivesdk

**Comment by singh043** [comment]
> U can fix the error loading anime page https://drive.google.com/file/d/1CcuWinkzQ3nJyC04dxY78i5mbmakr63B/view?usp=drivesdk

Thanks that prblm solved
 but still its showing different anime instead of mieruko its showin
