### ISSUE TITLE
I cant go down to score TV / can we have accounts on tv

### ISSUE THREAD

**Issue by Salamanka1212** [deceptions/no#16]
I cant score or go under progress thing

1. Go to anime info/page
2. Press right button
3. Scroll down to score

https://drive.google.com/file/d/1CzVSe8EkIjw0AQT0pU8m4S4HTsxu1nFm/view?usp=drivesdk

 - Android ?
 - 1.2.1
 - Sony tv

**Additional context**
Can we have different accounts so we can sync on different accounts on tv like Netflix

**Comment by deceptions** [comment]
Thank you for the video. I will try to have it fixed by next release. :+1:

**Comment by deceptions** [comment]
Has the issue been resolved in 1.2.2?

**Comment by Salamanka1212** [comment]
> Has the issue been resolved in 1.2.2?

No

**Comment by Salamanka1212** [comment]
Fixed😀
