### ISSUE TITLE
Questionsssssss

### ISSUE THREAD

**Issue by Salamanka1212** [deceptions/no#19]
Hopefully all of my dumb questions will be answered 😂

Do u plan to private the app? i dont want "no" to shut down again
Does gogoanime allow what ur doing?
Do u plan to make a discord room like shiro?
Will we have subscribed anime shows?
Will there be a way to see downloading videos on the app? I know its on the notification bar but can we have?
Thumbnails and titles?

TV
Is there a way to refresh the app on tv? hopefully there is i cant play/find latest episodes without refreshing the app
Multiple accounts?

**Comment by deceptions** [comment]
> Do u plan to private the app? i dont want "no" to shut down again

I have no plans of making the app private.
> Does gogoanime allow what ur doing?

Likely not, I have not notified nor talked to them.

> Do u plan to make a discord room like shiro?

I am considering it.

> Will we have subscribed anime shows?

Maybe.

> Will there be a way to see downloading videos on the app? I know its on the notification bar but can we have?
Thumbnails and titles?

Likely, but not too soon.

> Is there a way to refresh the app on tv?

No, but If you want to refresh the latest episode of an anime re-opening the anime info page is sufficient.
NOTE: Swiping down on the phone version does not refresh the home page, only the random poster.

> Multiple accounts?

Maybe.
