### ISSUE TITLE
Open settings > accounts to log in to your MAL account or swipe left on the anime info page and press login. On that page you can also set sync data, such as rating and progress once you have logged in.

### ISSUE THREAD

**Issue by Faizar123** [deceptions/no#21]
Open settings > accounts to log in to your MAL account or swipe left on the anime info page and press login. On that page you can also set sync data, such as rating and progress once you have logged in.

_Originally posted by @deceptions in https://github.com/deceptions/no/issues/20#issuecomment-924398354_

**Comment by Faizar123** [comment]
> Open settings > accounts to log in to your MAL account or swipe left on the anime info page and press login. On that page you can also set sync data, such as rating and progress once you have logged in.
> 
> _Originally posted by @deceptions in [#20 (comment)](https://github.com/deceptions/no/issues/20#issuecomment-924398354)_

![Uploading Screenshot_2021-09-22-14-31-45-78_c35b1f741f4ca208cd6e18660d53f924.jpg…]()

**Comment by Faizar123** [comment]
![Screenshot_2021-09-22-14-31-40-59_c35b1f741f4ca208cd6e18660d53f924](https://user-images.githubusercontent.com/70917974/134315765-f3249a31-2338-4c8e-a58b-feb03742037d.jpg)

**Comment by Faizar123** [comment]
> Open settings > accounts to log in to your MAL account or swipe left on the anime info page and press login. On that page you can also set sync data, such as rating and progress once you have logged in.
> 
> _Originally posted by @deceptions in [#20 (comment)](https://github.com/deceptions/no/issues/20#issuecomment-924398354)_

![Screenshot_2021-09-22-14-31-45-78_c35b1f741f4ca208cd6e18660d53f924](https://user-images.githubusercontent.com/70917974/134315838-587403d2-0463-4200-862e-9875a2740c9d.jpg)

**Comment by Faizar123** [comment]
Actually i logged in
But no option for mal sycn
Please fixed this
There's really no option

**Comment by deceptions** [comment]
Like i said in my first message, swipe to the left on the anime info page, like discord, to open a panel for MAL sync.

**Comment by Faizar123** [comment]
> Like i said in my first message, swipe to the left on the anime info page, like discord, to open a panel for MAL sync.

Now I'm feeling I'm a fool
Lol
Dev it's funny 🤣🤣🤣🤣
