### ISSUE TITLE
Slow Downloading speed

### ISSUE THREAD

**Issue by Benhirer** [deceptions/no#22]
- Wifi Speed           : 100mbps

⭐Realme 3 pro
 - Android version : 11
 - App version        : 1.2.2
 - Phone model      : RMX1851
 
⭐Lenovo Tab 7
 - Android version : 7.0
 - App version        : 1.2.2
 - Phone model      : Lenovo TB-304F

⭐Realme 7 pro
  - Android version : 11
  - App version        : 1.2.2
  - Phone model      : RMX2170

https://user-images.githubusercontent.com/88143961/136684447-32195dd4-3312-47da-9c93-2c352ac4b8b6.mp4

**Comment by deceptions** [comment]
https://github.com/deceptions/no/issues/13#issuecomment-932993162

**Comment by Benhirer** [comment]
> [#13 (comment)](https://github.com/deceptions/no/issues/13#issuecomment-932993162)

Ok.

**Comment by Salamanka1212** [comment]
Also speed depends on the gogoanime server
