### ISSUE TITLE
episode mark seen 

### ISSUE THREAD

**Issue by jeybsss** [deceptions/no#23]
**Describe the bug**
I don't know if this feature has already been implemented cause if it has been, then i am reporting a bug.

if episode is marked as seen and you press back and return to home, the anime you watched should now be in the next episode in the continue watching section instead of where you left off from the finished episode

**To Reproduce**
1. finish the episode and mark anime as seen
2. press back to return home
3. anime should be in the next episode in the continue watching section instead of where you left off in the finishes episode

**Screenshots**

**Please complete the following information:**
 - Android 7.0
 - 1.2.3
 - OPPO F3

**Additional context**

**Comment by deceptions** [comment]
Continue watching is based on a compile time percentage while marked as seen is user based. I will try to have this discrepancy fixed by next update.

**Comment by deceptions** [comment]
Should be fixed in latest update :+1:
