### ISSUE TITLE
Download page are slow

### ISSUE THREAD

**Issue by Salamanka1212** [deceptions/no#24]
When i have many downloads the download page opens slower, can the app be faster?

**To Reproduce**
1. Download many anime title
2. Click on download page

https://drive.google.com/file/d/1EEmNsoJy20EW5vHMbXFnCkveWgsGcahN/view?usp=drivesdk

**Please complete the following information:**
 - Android 11
 - 1.2.3
 - Realme8pro

**Additional context**
Old bug the past developer said his gonna fixed it but the app got taken down.

**Comment by Salamanka1212** [comment]
It was like 16 anime titles

**Comment by deceptions** [comment]
Sounds fixable :+1: 
Thank you for including a recording.

**Comment by deceptions** [comment]
Please try https://transfer.sh/AHhYkL/app-phone-beta.apk

**Comment by Salamanka1212** [comment]
> Please try https://transfer.sh/AHhYkL/app-phone-beta.apk

https://user-images.githubusercontent.com/87646218/137246415-a79076b1-d1fe-4dce-a0c8-c9adfc471ea8.mp4
Not fixed but its faster

**Comment by deceptions** [comment]
This is about as fast as I can make it https://transfer.sh/fxSh7M/app-phone-beta.apk

**Comment by Salamanka1212** [comment]
> This is about as fast as I can make it https://transfer.sh/fxSh7M/app-phone-beta.apk

https://user-images.githubusercontent.com/87646218/137422535-936516af-10fa-4d25-bfb6-2b7ada964ebe.mp4
So, not fixable?

**Comment by deceptions** [comment]
I might be able to cache it or similar to prevent reloading.
At least it does not make the whole app unresponsive like before.

**Comment by deceptions** [comment]
It should save the state now resulting in less loading. Try: https://transfer.sh/jvr3Co/app-phone-beta.apk
The apk also includes some experimental new UI changes.

**Comment by Salamanka1212** [comment]
> I might be able to cache it or similar to prevent reloading.
> At least it does not make the whole app unresponsive like before.
😀
I remember the old dev said that the download page uses older ui or whatever from the others thats why its like that

**Comment by Salamanka1212** [comment]
> It should save the state now resulting in less loading. Try: https://transfer.sh/jvr3Co/app-phone-beta.apk
Nice its a little bit faster hope it gets better😊
> The apk also includes some experimental new UI changes.
Idk why but the design is a bit boring

**Comment by Salamanka1212** [comment]
Update: Its kinda fine now with 16 titles its laggy when i tested it because i had 24 or more titles back then 😀

**Comment by deceptions** [comment]
Closing as it is about as optimized I can make it.

**Comment by Salamanka1212** [comment]
> Closing as it is about as optimized I can make it.

😔
