### ISSUE TITLE
Apk parsing issue android 12

### ISSUE THREAD

**Issue by GlitchSlayed** [deceptions/no#27]
**on Android 12 I can't get the apk to install as I get a apk parsing issue**

**To Reproduce**
1. Download apk
2. Try to install
3. See error

**Screenshots**

**Please complete the following information:**
 - Android version 12
 - App version Latest prerelease
 - Phone model Pixel 4

**Additional context**

**Comment by deceptions** [comment]
Try http://transfer.sh/nEOVBf/app-phone-beta.apk @GlitchSlayed @saipraveenbammidi 
I upgraded the SDK version which hopefully fixes this issue.

**Comment by parzival-cmd** [comment]
> Try http://transfer.sh/nEOVBf/app-phone-beta.apk @GlitchSlayed @saipraveenbammidi I upgraded the SDK version which hopefully fixes this issue.

Same error is showing, there was a problem while parsing.

**Comment by deceptions** [comment]
Second time's the charm: https://transfer.sh/9i0jMR/app-phone-beta.apk

**Comment by parzival-cmd** [comment]
> Second time's the charm: https://transfer.sh/9i0jMR/app-phone-beta.apk

Perfect, the beta apk is just working fine.
and thanks.
ps: showing error while loading anime page when I click on any anime.

**Comment by parzival-cmd** [comment]
> Second time's the charm: https://transfer.sh/9i0jMR/app-phone-beta.apk
Every other thing except installation in Android 12 is broken.

**Comment by deceptions** [comment]
> Every other thing except installation in Android 12 is broken.

I am unable to replicate any issues on my Emulator. Please do send a video.

**Comment by deceptions** [comment]
Does this issue remain in 1.2.5?

**Comment by deceptions** [comment]
Re-open if the issue remains.
