### ISSUE TITLE
Anilist button not working

### ISSUE THREAD

**Issue by Salamanka1212** [deceptions/no#29]
Anilist button doesn't work in any anime

**To Reproduce**
1. Go to info page, swipe left
2. Click on Anilist

https://user-images.githubusercontent.com/87646218/136956588-b37e226f-09cf-4e0b-9a8c-b6b85486ef71.mp4

**Please complete the following information:**
 - Android 12
 - 1.2.3
 - Realme8pro

**Comment by deceptions** [comment]
Will fix by next update :+1:
