### ISSUE TITLE
all out s1 issue and full season download at once option

### ISSUE THREAD

**Issue by singh043** [deceptions/no#3]
It would be great if u can add a button to download a full season at once 
And i opened subbed version of all out s1 it showed error could not extract stream can u fix that

**Comment by deceptions** [comment]
Batch downloading likely not coming soon.
Send screenshot of the full extract stream error because it is working flawlessly for me :^)

**Comment by singh043** [comment]
![IMG_20210929_221739](https://user-images.githubusercontent.com/90082683/135313905-e2b5ac74-7748-4f64-a7a9-0be9868483e6.jpg)
![IMG_20210929_221802](https://user-images.githubusercontent.com/90082683/135313911-af6e4c19-b7de-4df7-a207-b9894488f714.jpg)
Now its showing no links found for some anime other animes r working fine
Earlier no extracted stream was shown

**Comment by singh043** [comment]
![IMG_20210929_221802](https://user-images.githubusercontent.com/90082683/135315511-1cfb7837-374d-4e1f-9f14-90f2c8ab7352.jpg)
![IMG_20210929_221739](https://user-images.githubusercontent.com/90082683/135315523-b16a5449-dfe9-4064-ae62-5f5f5ac2821c.jpg)

Now its showing no links found for some anime (case closed e1 sub n all out both sub n dub) other animes r working fine
Earlier no extracted stream was shown only for sub of all out 
Till monday there was no issue dont know now what happened my internet is also good
