### ISSUE TITLE
Hey ruski bro 

### ISSUE THREAD

**Issue by cutterchop** [deceptions/no#3]
Hey no description dude, we noticed the app has multiple bugs as you are aware, I want you to be in a server of ours to give feed back and what we think it's a small server so join us and take a look

https://discord.gg/52Q3NVcQ

Пожалуйста, приходи, детка, иначе ^_^

**Comment by deceptions** [comment]
I am not going to join a discord server any time soon.
Please open discussions or issues for feedback :)
