### ISSUE TITLE
Hide setting causes crashing

### ISSUE THREAD

**Issue by tywentghxst** [deceptions/no#32]
It appears that hiding the sub or dub causes crashing on the app.

**To Reproduce**
1. Go to settings, general, hide dub or sub, then click on an anime after and it causes crashing.

**Comment by deceptions** [comment]
Next release will feature a fix. 
Thank you for reporting :+1:

**Comment by tywentghxst** [comment]
Thanks! Thanks for your work on bringing our beautiful shiro app back too! Any chance you have a discord for the app I can join?

**Comment by deceptions** [comment]
A discord server is in my project plan. I am a bit reluctant however as managing bugs and feature requests in a discord server is much more messy than on GitHub.

**Comment by tywentghxst** [comment]
Very true, bots would definitely help too, well if you decide to start one and would like help managing it, I'd be willing to give you a hand if you'd like.

**Comment by deceptions** [comment]
> bots would definitely help too

If you do know of any bots which can manage issues and requests please do tell. I can't be bothered creating my own bot.

**Comment by tywentghxst** [comment]
I remember a few Ive seen some old discord I was on for it, I'll look into it more when I'm home and will send what I find here.

**Comment by deceptions** [comment]
Is this fixed in the latest update?

**Comment by tywentghxst** [comment]
I was testing it out last night and it appears to have been, thank you much Deception!
