### ISSUE TITLE
weird.....

### ISSUE THREAD

**Issue by mckXsun** [deceptions/no#36]
https://streamtape.com/v/paB2rjaYpghrkWd/Screenrecording_20211015_143511.mp4

**Comment by Salamanka1212** [comment]
Android 12?

**Comment by mckXsun** [comment]
Android 11

**Comment by mckXsun** [comment]
vivo z1 pro
app latest verion it was happing in previous ver too

**Comment by deceptions** [comment]
I am unable to replicate. No idea what causes this issue :confused:

**Comment by Salamanka1212** [comment]
Maybe try to reinstall the app

**Comment by mckXsun** [comment]
I tried everything i could, not working.
After reinstalling it isn't even opening at all 😂

**Comment by mckXsun** [comment]
![Screenshot_20211016_144128](https://user-images.githubusercontent.com/83224209/137581884-fd135c7c-b267-4f6e-a044-160d22eb25b1.jpg)
As soon as episode started it was marked as read, after i tapped next episode button.
And my app is totally bugged even tho i reinstalled.
![Screenshot_20211016_144230](https://user-images.githubusercontent.com/83224209/137581923-2a76c801-f6ec-467c-a4f5-a9c7c1ba4602.jpg)
![Screenshot_20211016_144239](https://user-images.githubusercontent.com/83224209/137581925-bc3e749a-a833-492a-94c3-93ea8c902c35.jpg)

**Comment by mckXsun** [comment]
none of the anime page load now

**Comment by mckXsun** [comment]
Should i send u my backup if it could help?

**Comment by mckXsun** [comment]
I downgraded app to 1.2.2 then updated then it seems to be working when i restored problem came back.

**Comment by mckXsun** [comment]
Again same problem seems like something is wrong 😂
