### ISSUE TITLE
Problem playing any anime for Indian users

### ISSUE THREAD

**Issue by AnixNyk** [deceptions/no#37]
**Describe the bug**
I am from India and this problem started from today morning. Whenever I try to play anything it shows no link found and also the search is not working for me as well. (I think this problem is only for Indian users as I think gogoanime.vc has been blocked in India and also I tried using a vpn the app just worked fine then)

**To Reproduce**
1. Go to 'search'
2. Try to search any anime it won't work
3. Try to open any anime from home screen it will show "error loading anime page"

**Screenshots**
![Screenshot_2021-10-15-23-00-12-962_com deceptions no](https://user-images.githubusercontent.com/92598688/137529122-2e01c66c-e996-47e9-91f5-259e8fcb6879.jpg)
![Screenshot_2021-10-15-23-00-21-501_com deceptions no](https://user-images.githubusercontent.com/92598688/137529153-d99a3d1d-2c5d-4f20-9de8-59626b26e3d0.jpg)

**Please complete the following information:**
 - Android version- android 11
 - App version- latest version 1.2.4
 - Phone model- Motorola edge 20

**Additional context**

**Comment by deceptions** [comment]
I might add an option to change the Gogoanime url.
It would not be useful adding the option if all of them are blocked. Please test the following sites without VPN and tell me which are blocked so I can fix it accordingly.

https://gogoanime.vc/ (to double check)
https://gogoanime.pe/
https://gogoanime.pro/
https://gogoanime.lol/
https://gogoanime.studio/home/
https://gogoanime.city/home/

Not clones, but good to know if blocked as they can be used if the Gogoanime clones do not work:
https://streamani.net/
https://goload.one/

**Comment by AnixNyk** [comment]
https://gogoanime.pe/
https://gogoanime.studio/home/
https://gogoanime.city/home/
https://goload.one/

These are the only sites which are WORKING in India without any VPN

**Comment by deceptions** [comment]
Thank you for testing! I made .pe default.
Please try https://transfer.sh/Hn4Vti/app-phone-beta.apk

**Comment by AnixNyk** [comment]
This app is working totally fine... Thank you

**Comment by mckXsun** [comment]
> Thank you for testing! I made .pe default. Please try https://transfer.sh/Hn4Vti/app-phone-beta.apk

This seems to be working for me too

**Comment by Salamanka1212** [comment]
> > Thank you for testing! I made .pe default. Please try https://transfer.sh/Hn4Vti/app-phone-beta.apk
> 
> This seems to be working for me too

U can close ur issue

**Comment by Shahabaz5** [comment]
I am having same issue.It worked like a week ago.Now it shows no links found and buffers a lot.Using VPN solves the buffering.

**Comment by deceptions** [comment]
> I am having same issue.It worked like a week ago.Now it shows no links found and buffers a lot.Using VPN solves the buffering.

Did you try 1.2.5?

**Comment by Shahabaz5** [comment]
Yes.Iam currently using that version.It worked a week ago,but now it buffers.

**Comment by Shahabaz5** [comment]
https://user-images.githubusercontent.com/88045338/138031940-f4e895c1-00ec-483c-97a8-51c942eada61.mp4
Please take a look at this screen record.It takes forever to load.

**Comment by deceptions** [comment]
> Please take a look at this screen record.It takes forever to load.

It does load eventually. I can not improve your connection to the Vidstream servers. Switch source or quality if you are experiencing slow loading in the player.

**Comment by deceptions** [comment]
1.3.0 Should solve any ISP blacklist issues common in India.

**Comment by deceptions** [comment]
Re-open if this issue returns or has not been fixed.
