### ISSUE TITLE
Can't click on anything when I search for stuff + also whenever I scroll to the right to add said anime it's just black 

### ISSUE THREAD

**Issue by Bagoftakis** [deceptions/no#40]
**Describe the bug**
So basically, any anime that I try searching for some reason it won't let me click on anything. Also when I scroll to add it to my mal list etc it's just black 

**To Reproduce**
1. Go to My hero academia s4 
2. Click on  just try to click on any episode
3. Go to the right (this is for the mal glitch) and it's just black all black. Only thing I can see is just the "log in to mal and anilist" 
4. See error, the error is that I can't click on anything 

**Screenshots**
![PicsArt_10-18-05.47.52.png](https://user-images.githubusercontent.com/92281282/137825798-c3e839aa-d7f9-4456-9af3-f6515be6ca1c.png)

**Please complete the following information:**
 - Android version-Android tv 
 - App version- 1.2.5 (also happened on 1.2.3 and 1.2.4)
 - Phone model-none lol

**Additional context**

**Comment by Bagoftakis** [comment]
I want to keep on mind you don't have to go on my hero academia, I just used it as an example. So far the only anime's that work for me are in homepage etc.

**Comment by Salamanka1212** [comment]
Sorry to say this but did u try to login to Mal or anilist cause if not f#c# urself

**Comment by Bagoftakis** [comment]
> Sorry to say this but did u try to login to Mal or anilist cause if not f#c# urself

Yes I was able to log in to mal

**Comment by Bagoftakis** [comment]
> I want to keep on mind you don't have to go on my hero academia, I just used it as an example. So far the only anime's that work for me are in homepage etc. 

Also another thing. Just ignore the buttom part where I included my phone mode etc. IM ON ANDROID TV (google tv btw)

**Comment by Salamanka1212** [comment]
My bad😂😂

**Comment by deceptions** [comment]
I do not understand the login issue. Pressing right is supposed to show you a login page (or a sync page if you are logged in).
Go to Settings -> Accounts and tell me if it says you are logged in.

> 4. See error, the error is that I can't click on anything

> Can't click on anything when I search for stuff

That is very undescriptive. Do you mean that you cannot:
1) Go down and click on the search results
2) Click on anything when you have opened a search result
3) Click on the login button

What Android Version number? (E.g 8.1)

A video would be much appreciated.

**Comment by Bagoftakis** [comment]
> I do not understand the login issue. Pressing right is supposed to show you a login page (or a sync page if you are logged in). Go to Settings -> Accounts and tell me if it says you are logged in.
> 
> > 1. See error, the error is that I can't click on anything
> 
> > Can't click on anything when I search for stuff
> 
> That is very undescriptive. Do you mean that you cannot:
> 
>     1. Go down and click on the search results
> 
>     2. Click on anything when you have opened a search result
> 
>     3. Click on the login button
> 
> 
> What Android Version number? (E.g 8.1)
> 
> A video would be much appreciated.
This is what I meant by the log in issue as normally it looks like that. 
https://media.discordapp.net/attachments/898905847147671633/900183771452678174
/PicsArt_10-19-05.47.50.png

(video link) (sorry for the low quality https://media.discordapp.net/attachments/898905847147671633/900193862209916978/8mb.video-RA2-FFsiVQpL.mp4

**Comment by deceptions** [comment]
Does this issue remain in 1.3.1?
