### ISSUE TITLE
Crashes when download settings page is clicked without download page losding

### ISSUE THREAD

**Issue by Salamanka1212** [deceptions/no#41]
Might only crash when downloads are 16+ titles

**To Reproduce**
1. Go to downloads fast
2. Click on settings
3. Repeat

https://drive.google.com/file/d/1Frsc-ysYXtNPW0jLqoBcqIBUihY24l1P/view?usp=drivesdk

**Please complete the following information:**
 - Android 11
 - App 1.2.5
 - Realme8pro

**Comment by deceptions** [comment]
Try 1.3.0

**Comment by Salamanka1212** [comment]
Thanks!
