### ISSUE TITLE
buffers alot in app

### ISSUE THREAD

**Issue by mckXsun** [deceptions/no#48]
When i play the anime episode in app it buffers alot but when i play it on gogoanime it runs smoothly.... 
Android 11
App latest version

**Comment by singh043** [comment]
Even I have same issue

**Comment by mckXsun** [comment]
Happens with both gogo and vid

**Comment by Remon8** [comment]
Yes i just checked gogoanime and  vidstream are buffering alot

**Comment by deceptions** [comment]
I can not improve your connection to the VidStream servers. All video loading is done by ExoPlayer and out of my hands. Use other sources if possible.

**Comment by mckXsun** [comment]
Extractors sometimes works and sometimes not even tho gogoanime site works pretty good in browser. No worries thanks for the response.
