### ISSUE TITLE
In anime show tracker

### ISSUE THREAD

**Issue by tywentghxst** [deceptions/no#49]
There used to be a area at the top of every show that you clicked on telling you what episode you last watched from your anilist for the said show, was that removed or the old app? If so could you please add it back.

**Comment by Salamanka1212** [comment]
Swipe left for that and right for recommendations

**Comment by tywentghxst** [comment]
> Swipe left for that and right for recommendations

Oh god I'm dumb, haha thank you!

**Comment by Salamanka1212** [comment]
U can close the issue join discord for questions like this
