### ISSUE TITLE
App does not open

### ISSUE THREAD

**Issue by Art0343** [deceptions/no#5]
After the latest update - 1.2.0
The app does not open 
![Screenshot_20211001-102404](https://user-images.githubusercontent.com/91286865/135567232-cb0c9b45-03de-4c5e-87cf-6d28033deed6.png)

 - Android version - 8
 - App version- 1.2.0
 - Phone model-  XT1902-3/ Lenovo k8 note

**Comment by 7mostov5** [comment]
Same

**Comment by deceptions** [comment]
Should be fixed in 1.2.1, re-open if that is not the case.
