### ISSUE TITLE
error.

### ISSUE THREAD

**Issue by mckXsun** [deceptions/no#53]
Episodes doesn't play, used both domains .wiki and .pe
Extractor fails most of the time.
Used dns over https doesn't help.
Used vpn and in it sometimes work.
App version latest.
Android 11.
![Screenshot_20211106_221440](https://user-images.githubusercontent.com/83224209/140617304-c58884ea-c8da-4eba-af8d-4cc97a30b4db.jpg)

**Comment by ghost** [comment]
> Episodes doesn't play, used both domains .wiki and .pe Extractor fails most of the time. Used dns over https doesn't help. Used vpn and in it sometimes work. App version latest. Android 11. ![Screenshot_20211106_221440](https://user-images.githubusercontent.com/83224209/140617304-c58884ea-c8da-4eba-af8d-4cc97a30b4db.jpg)

In links loading sources select all links except gogo ,streamtape and vidstream and 
Keep dns over https as google use vpn n 
play again it wl work

**Comment by mckXsun** [comment]
Error: no links found

> > Episodes doesn't play, used both domains .wiki and .pe Extractor fails most of the time. Used dns over https doesn't help. Used vpn and in it sometimes work. App version latest. Android 11. ![Screenshot_20211106_221440](https://user-images.githubusercontent.com/83224209/140617304-c58884ea-c8da-4eba-af8d-4cc97a30b4db.jpg)
> 
> In links loading sources select all links except gogo ,streamtape and vidstream and Keep dns over https as google use vpn n play again it wl work

Error no links found

**Comment by mckXsun** [comment]
Iss okay imma closing LoL
