### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by JasonSmith20** [deceptions/no#58]
Are you planning on including any movies or tv series in the future

**Comment by Salamanka1212** [comment]
Kuro is an ANIME APP but deceptions said he might add tv/movie series and that the app will be scraping on 3 sites

**Comment by Salamanka1212** [comment]
Im against on people wanting to add none anime sites(hopefully its only 3 anime sites)

**Comment by JasonSmith20** [comment]
Hopefully he adds https://www.wcofun.com/  as it has cartoons and anime alike with a huge library

**Comment by JasonSmith20** [comment]
I ask this because this app has obvious potential
