### ISSUE TITLE
It crashes every time. 

### ISSUE THREAD

**Issue by Ink25** [deceptions/no#60]
**Describe the bug**
Every time I try to open an anime, it stops working. 
Even tried re-installing the app 

**To Reproduce**
1. Open the app
2. Click on your list
3. Click on any anime 
4. It stops working

**Video**
https://user-images.githubusercontent.com/85929295/142577241-47b6105d-9540-4133-b540-88599ba99dde.mp4

**Device Information:**
 - Android version 5.0.2
 - App version 1.6.4
 - Phone model Vivo Y51L

**Additional context**
The App was really nice and smooth before this update
Please fix this issue as soon as possible. 

Thanks.

**Comment by deceptions** [comment]
> The App was really nice and smooth before this update

Which update specifically works? The beta or the latest stable release? Please give a number so I can narrow down the bug.

**Comment by Ink25** [comment]
> > The App was really nice and smooth before this update
> 
> Which update specifically works? The beta or the latest stable release? Please give a number so I can narrow down the bug.

The 1.5.5 update was working smoothly 
Actually I didn't update this app after 1.5.5.
I directly updated to 1.6.4 and it's not working

**Comment by deceptions** [comment]
I assume the closing is unintentional. Can you please track down the version it stopped working on. You should be able to downgrade without losing any data.

**Comment by Ink25** [comment]
It stopped working on 1.6.4.
So I'm using 1.5.5 and it's working well.

**Comment by deceptions** [comment]
1.6.5 should work.

**Comment by rahaaatul** [comment]
> 1.6.5 should work.

`1.6.4` was crashing on my Android 5 TV. `1.6.5` fixed it. Thanks, @deceptions .

_But now,_
- _Clicking **Accounts** crash in settings._
- _**Search** and click on Anime crash._

**Comment by Ink25** [comment]
Yeah it's working in 1.6.5
