### ISSUE TITLE
Renderer Error

### ISSUE THREAD

**Issue by rahaaatul** [deceptions/no#64]
**Describe the bug**
Can't play any anime. Everytime I click on the play button, it loads for some time and says renderer error.

**To Reproduce**
1. Go to any anime.
2. Click on play.
3. See error.

**Screenshots**
![IMG_20211127_004628.jpg](https://user-images.githubusercontent.com/86149861/143621442-1305bfc6-4cfc-48b9-8a55-ff0becb2d31c.jpg)

**App Version: 1.6.5**

**Device Information:**
```
Android Verison: 5.1.1
Core Architecture: 2x ARM Cortex-A53 @ 1416 MHZ
Instruction Set: 64-bit ARMv8-A (32-bit Mode)
CPU Revision: r0p4
CPU Cores: 2 
CPU Clock Range: 100 - 1416 MHz
Core 1Clock: 1200 MHz 
Core 2 Clock: 1200 MHz
Scaling Governor: interactive
Supported ABIs: armeabi-v7a, armeabi 
Supported 32-bit ABIs: armeabi-v7a, armeabi 
AES: Supported 
NEON: Supported 
PMULL: Supported 
SHA1: Supported 
SHA2: Supported
Device Type: TV
Manufacturer: amlogic
Model: SMART_TV
Brand: Android
Board: r34a5
Device: r34a5
Hardware: a logic
Platform: txhd
Product: r34a5
Serial: B20010220-0A01785
```

**Additional context**
Plays fine in 1.5.2

**Comment by deceptions** [comment]
I can not fix Exoplayer issues.
