### ISSUE TITLE
New update

### ISSUE THREAD

**Issue by Jasonsmith236** [deceptions/no#68]
Nice new update no problems so far keep up the good work 👍👍😁🌟

**Comment by rahaaatul** [comment]
Dude 🤦‍♂️.

Open issue if you have any issue with the app.

**Comment by Jasonsmith236** [comment]
And dude I am just trying to show some support this is the only way I know how.

**Comment by rahaaatul** [comment]
> And dude I am just trying to show some support this is the only way I know how.

Go to discord channel.

**Comment by Jasonsmith236** [comment]
Ok
