### ISSUE TITLE
No links found

### ISSUE THREAD

**Issue by Jiimaa** [deceptions/no#7]
v1.2.1
No links found

![Screenshot_2021-10-01-22-28-15-73](https://user-images.githubusercontent.com/91742880/135637396-f2c09db9-e4b6-476b-b61b-2f04d3a4b4e1.jpg)

Android 8.1
 v1.2.1
Oppo A5s

**Comment by Benhirer** [comment]
Apk Showing :  No links found
Version : 1.2.1
Lenovo Tab 7
Android 7.0
That's why I reinstated apk v1.1.4 for continue watching anime.

**Comment by deceptions** [comment]
How am I supposed to help if you do not give what show you are trying to load :confused: 

All link loading on the shows I have tested works fine for me.

**Comment by Benhirer** [comment]
I am trying to load Barakamon (Dub).I have checked 3 or 4 anime but results are same.
![Screenshot_2021-10-01-22-51-14-311](https://user-images.githubusercontent.com/88143961/135661751-9d5787b5-e254-4d71-aaea-791944de24bb.jpeg)

**Comment by Jiimaa** [comment]
> How am I supposed to help if you do not give what show you are trying to load 😕
> 
> All link loading on the shows I have tested works fine for me.

I tried all sorts of different anime (including the random one's) in v1.2.1 but the results are the same. 

![Screenshot_2021-10-01-22-16-23-76](https://user-images.githubusercontent.com/91742880/135663302-d72556e2-720d-448b-bead-5f94c5824262.jpg)

So I just reinstall the v1.1.4 since it work's fine.

**Comment by Benhirer** [comment]
See this video.😃

**Comment by Benhirer** [comment]
> How am I supposed to help if you do not give what show you are trying to load 😕
> 
> All link loading on the shows I have tested works fine for me.

😃See this recording please. Android 7.0, Lenovo Tab 7 and Apk v1.2.1. 


https://user-images.githubusercontent.com/88143961/135704293-bc72a88d-6d13-453e-93f4-dbf5d5f305a9.mp4


⭐ Recording for Apk v1.1.4.


https://user-images.githubusercontent.com/88143961/135704724-2915e954-fa08-4349-a59b-85769bd1df87.mp4

**Comment by deceptions** [comment]
Looks suspiciously much like ISP blockage.
Can you load https://goload.one/streaming.php?id=MzUxOA== in your phone browser?
Try using a different DNS or VPN and see if it works. If it turns out to be ISP blockage I will add a switch for switching to streamani.

**Comment by Jiimaa** [comment]
> Looks suspiciously much like ISP blockage. Can you load https://goload.one/streaming.php?id=MzUxOA== in your phone browser? Try using a different DNS or VPN and see if it works. If it turns out to be ISP blockage I will add a switch for switching to streamani.

Yes, I can load that link but it still doesn't work on v1.2.1, I also tried using vpn but the results are the same.

**Comment by deceptions** [comment]
That is very weird, I will send you a changed apk soon which might work.

**Comment by Benhirer** [comment]
> Looks suspiciously much like ISP blockage. Can you load https://goload.one/streaming.php?id=MzUxOA== in your phone browser? Try using a different DNS or VPN and see if it works. If it turns out to be ISP blockage I will add a switch for switching to streamani.

Yes, that link is load in my browser without any problem.

> That is very weird, I will send you a changed apk soon which might work.

Please do 😊.

**Comment by deceptions** [comment]
Please try http://transfer.sh/apD2oT/app-phone-beta.apk @Benhirer @Jiimaa

**Comment by Jiimaa** [comment]
> Please try http://transfer.sh/apD2oT/app-phone-beta.apk @Benhirer @Jiimaa

Still the same result 

![Screenshot_2021-10-03-12-35-52-35](https://user-images.githubusercontent.com/91742880/135740185-87774687-c355-4bfa-ab84-11d0544ce0f7.jpg)
![Screenshot_2021-10-03-12-38-27-23](https://user-images.githubusercontent.com/91742880/135740193-bc2f4bb5-8c03-475e-944b-030f2310d62c.jpg)

**Comment by Benhirer** [comment]
> Please try http://transfer.sh/apD2oT/app-phone-beta.apk @Benhirer @Jiimaa

😐Nothing changed.

https://user-images.githubusercontent.com/88143961/135740478-75defa3c-e21f-4cbb-a712-a28bde94797d.mp4

Model number : Lenovo TB-7304F
Android Version : 7.0
CPU : MediaTek®MT8167D

**Comment by deceptions** [comment]
Thanks for testing :smile: 
I'm sending another apk soon. This time with proper error catching.

**Comment by deceptions** [comment]
Added a toast showing what is wrong and added a separate try catch meaning that it should work at least partially. http://transfer.sh/2t3lX6/app-phone-beta.apk

**Comment by Jiimaa** [comment]
> Added a toast showing what is wrong and added a separate try catch meaning that it should work at least partially. http://transfer.sh/2t3lX6/app-phone-beta.apk

I've tried to load 10 animes but it still have the same problem previous problem, It still shows "No links found", I also tried using VPN or changing DNS but the results are the same. But im glad that you're working on it. I hope you could fix this soon. 😁😁

**Comment by deceptions** [comment]
Not even showing an error Toast? My theories keeps getting dis-proven :sob:
I honestly have no clue anymore. Please post your [logcat](https://www.xda-developers.com/how-to-take-logs-android/) if possible.

**Comment by Benhirer** [comment]
> Not even showing an error Toast? My theories keeps getting dis-proven 😭 I honestly have no clue anymore. Please post your [logcat](https://www.xda-developers.com/how-to-take-logs-android/) if possible.

See😥.
[Log_2021-10-03_20-48-15.txt](https://github.com/deceptions/no/files/7273663/Log_2021-10-03_20-48-15.txt)

**Comment by Jiimaa** [comment]
> Not even showing an error Toast? My theories keeps getting dis-proven 😭 I honestly have no clue anymore. Please post your [logcat](https://www.xda-developers.com/how-to-take-logs-android/) if possible.

I'm ashamed to say that I am not deep into programming to basically understand how to get the logcat since I don't have PC/Laptop to do so, but @Benhirer might have.

Edit: Yeah he have it 😂

**Comment by Benhirer** [comment]
> > Not even showing an error Toast? My theories keeps getting dis-proven 😭 I honestly have no clue anymore. Please post your [logcat](https://www.xda-developers.com/how-to-take-logs-android/) if possible.
> 
> I'm ashamed to say that I am not deep into programming to basically understand how to get the logcat since I don't have PC/Laptop to do so, but @Benhirer might have.
> 
> Edit: Yeah he have it 😂

I searched on google for how to get logcat and got an app from play store called 'Logcat Extreme' then I use to get this logcat. I don't know that is right file 😅😅.

**Comment by deceptions** [comment]
The log is unfortunately missing anything anything useful. Either you are missing permissions or the app does not capture it properly, try searching for 'deceptions' instead of using the app specific feature.

I have tried and failed to replicate this issue on 4 different devices and I am unable to figure out what causes this as all the new code is in a try catch. :confused: 
As I can not replicate it I can not fix the issue without logs.

**Comment by Jiimaa** [comment]
> The log is unfortunately missing anything anything useful. Either you are missing permissions or the app does not capture it properly, try searching for 'deceptions' instead of using the app specific feature.
> 
> I have tried and failed to replicate this issue on 4 different devices and I am unable to figure out what causes this as all the new code is in a try catch. 😕 As I can not replicate it I can not fix the issue without logs.

Yeah I think only Rooted Phones (Phones w/custom ROMs) can record the logcat which required PC and such as it says on the User Guide of the app.

![Screenshot_2021-10-04-01-50-51-86](https://user-images.githubusercontent.com/91742880/135765583-e206c946-102e-45fa-a611-62f8cab63151.jpg)

**Comment by Mehafil07** [comment]
> Please try http://transfer.sh/apD2oT/app-phone-beta.apk @Benhirer @Jiimaa

This one is working Tnx bro ❤️

**Comment by kokoronikui** [comment]
I also have 2 tablets that don't work with 1.2.1. Working fine with 1.1.4. Both giving no links found error as well.

Both running Android 8 with different processors. I have 2 phones on A11 running 1.2.1 with no issues. Also a mibox 4k with A9 TV os running TV version 1.2.1 properly as well 
![IMG_20211005_101409](https://user-images.githubusercontent.com/19528306/135952097-65f825b5-ecba-41a1-9435-dbd32deeecd7.jpg)
![IMG_20211005_104415](https://user-images.githubusercontent.com/19528306/135952105-f2aedcee-7d4e-4028-8f92-eb3ca1a86d40.jpg)

**Comment by deceptions** [comment]
Since I have no logs I tried removing some of the new code to figure out the cause. Please try:
http://transfer.sh/NOUzKY/1.apk
and
http://transfer.sh/TlQr71/2.apk
and
http://transfer.sh/kxT8fE/3.apk
and tell me which of them works, if any of them work.

**Comment by Jiimaa** [comment]
> Since I have no logs I tried removing some of the new code to figure out the cause. Please try: http://transfer.sh/NOUzKY/1.apk and http://transfer.sh/TlQr71/2.apk and http://transfer.sh/kxT8fE/3.apk and tell me which of them works, if any of them work.

Umm I don't know if this is weird or what but they are all working on my phone

**Comment by Jiimaa** [comment]
> Since I have no logs I tried removing some of the new code to figure out the cause. Please try: http://transfer.sh/NOUzKY/1.apk and http://transfer.sh/TlQr71/2.apk and http://transfer.sh/kxT8fE/3.apk and tell me which of them works, if any of them work.

1,2 and 3 works fine 😁

**Comment by Narux07** [comment]
> > Since I have no logs I tried removing some of the new code to figure out the cause. Please try: http://transfer.sh/NOUzKY/1.apk and http://transfer.sh/TlQr71/2.apk and http://transfer.sh/kxT8fE/3.apk and tell me which of them works, if any of them work.
> 
> 1,2 and 3 works fine 😁

Same goes to me😙

**Comment by Benhirer** [comment]
> Since I have no logs I tried removing some of the new code to figure out the cause. Please try: http://transfer.sh/NOUzKY/1.apk and http://transfer.sh/TlQr71/2.apk and http://transfer.sh/kxT8fE/3.apk and tell me which of them works, if any of them work.

😊 It works great.

**Comment by kokoronikui** [comment]
> Since I have no logs I tried removing some of the new code to figure out the cause. Please try: http://transfer.sh/NOUzKY/1.apk and http://transfer.sh/TlQr71/2.apk and http://transfer.sh/kxT8fE/3.apk and tell me which of them works, if any of them work.

All 3 working with my tablets now when 1.2.1 didn't. 1 and 2 is more or less similar with identical server providers but no.3 with all vidstream ones load an episode the fastest without the need of shuffling through other servers like 1 and 2

**Comment by Benhirer** [comment]
> > Since I have no logs I tried removing some of the new code to figure out the cause. Please try: http://transfer.sh/NOUzKY/1.apk and http://transfer.sh/TlQr71/2.apk and http://transfer.sh/kxT8fE/3.apk and tell me which of them works, if any of them work.
> 
> All 3 working with my tablets now when 1.2.1 didn't. 1 and 2 is more or less similar with identical server providers but no.3 with all vidstream ones load an episode the fastest without the need of shuffling through other servers like 1 and 2

Not all anime load from vidstream server that's why we need different varieties of serves in such case.😃

**Comment by deceptions** [comment]
Nice! I am releasing this officially then :+1:
