### ISSUE TITLE
There is a login????

### ISSUE THREAD

**Issue by VardaanMak** [deceptions/no#73]
I am a new user and I was just looking at the app when I went to the setting and toped on the kuro logo it shows not logged in. Os is there a login page or process that will come or not showing up

If there is a process to login can someone tell me how to do it 

Hope you look forward to this issue
![Screenshot_2021-12-27-13-52-46-384_com deceptions no](https://user-images.githubusercontent.com/96719237/147451351-3ce5a819-b35b-4345-ba86-68aaaf041c5c.jpg)

**Comment by deceptions** [comment]
You can log in to MAL and AniList to sync your progress. See account settings.
Swipe right in the anime page to show your tracker stats.
