### ISSUE TITLE
Videos not playing at low resolution

### ISSUE THREAD

**Issue by Dvixe** [deceptions/no#78]
**Describe the bug**

**To Reproduce**

**Screenshots**

**Please complete the following information:**
 - Android version
 - App version
 - Phone model

**Additional context**

**Comment by Redddtt** [comment]
All the video quality are working perfectly fine, try changing ur dns over https to fix this

**Comment by deceptions** [comment]
I am unable to replicate. Update to 1.8.4 and send a video.

**Comment by deceptions** [comment]
Closed due to inactivity.
