### ISSUE TITLE
Retaining old downloads

### ISSUE THREAD

**Issue by jeyjai** [deceptions/no#81]
I get all me downloads in my gallery, so i tried the old .nomedia method which worked in gallery but in Kuro all downloads were gone with no way of getting then back even with removing the .nomedia file.
I still have all the files in the correct download folder but no way for kuro to detect them again.
This has happened once before, can't remember if i just had to remove cc and renstall the the app so i could be wrong.
I'm just guessing here but seems like Kuro using a db to sort out unwanted media but once a legitimate media is gone it's gone forever.

Maybe this can be added or reworked to readd legitimately downloaded files, maybe through hashing out something. And a scan button to not slow down the app.
Thnx

**Comment by Redddtt** [comment]
Atleast im not the only one
