### ISSUE TITLE
Episode's Title, description and thumbnail.

### ISSUE THREAD

**Issue by ghost** [deceptions/no#83]
**Describe the bug**

**To Reproduce**

**Screenshots**

**Please complete the following information:**
 - Android version
 - App version
 - Phone model

**Additional context**
Add any other context about the problem here. Please fix it

**Comment by Redddtt** [comment]
It has already been listed on issue #12 
If ur having issues like not having titles on some episodes keep in mind its still experimental

**Comment by deceptions** [comment]
Duplicate.
