### ISSUE TITLE
Continue watching bug - Red.

### ISSUE THREAD

**Issue by Redddtt** [deceptions/no#86]
Finishing the last/latest episode of an anime until it says no links found marks the next episode in the continue watching of the tv app as watched 

1. Finish the last/latest episode of an anime until it says no links found
2. Go to home/continue watching
3. See error

https://drive.google.com/file/d/1DthAWx-IemJqT9N-Zw7eom7LLZndug5i/view?usp=drivesdk

 - ?
 - 1.8.4
 - Sony Bravia 4k ur3

**Comment by Adi-MayNotSpeak** [comment]
Is it even an issue , you can just dismiss it from there

**Comment by Redddtt** [comment]
> Is it even an issue , you can just dismiss it from there

Please stfu😊, I've been reporting a ton of bugs since then and far as i know this is an issue.

**Comment by deceptions** [comment]
> Is it even an issue , you can just dismiss it from there

Leave that matter to the developers to decide. 
It certainly looks like a real bug in the auto-play system for TV.

**Comment by deceptions** [comment]
Fixed next update.
