### ISSUE TITLE
Leave anime page - Red.

### ISSUE THREAD

**Issue by Redddtt** [deceptions/no#88]
Leaving the app on other pages while in the anime page (except with ur app startup page settings) then going back after waiting to get the splash screen again then clicking on the page where u left the app in the anime page puts it in the anime page

**To Reproduce**
1. Go to an anime page
2. Go home/dont use the app for 30 mins or so to get splash screen again
3. Press the page where u left of 

https://drive.google.com/file/d/1EDRgvCYcps68dyjscaBCHeGeVRuQeSkU/view?usp=drivesdk

 - Android 11
 - 1.8.4

**Comment by deceptions** [comment]
Not a bug.
