### ISSUE TITLE
Library navigation bug - Red.

### ISSUE THREAD

**Issue by Redddtt** [deceptions/no#89]
Cant scroll down to the bottom of the library of the tv app it just stops

**To Reproduce**
1. Go to library
2. Scroll down
3. See error

https://drive.google.com/file/d/1EPv8ESikHbOVJFMxHOhm824cj9ZUOBpT/view?usp=drivesdk

 - 1.8.4
 - bravia 4k ur3

**Comment by deceptions** [comment]
Fix coming next release.
