### ISSUE TITLE
Is this gogo problem or app?

### ISSUE THREAD

**Issue by Salamanka1212** [deceptions/no#9]
Idk if this is a bug but when I try to watch its not loading properly, maybe its gogoanime problem

1. Go to any video
2. Click on any links from 1080 to 720
3. See error

 - Android 11
 - 1.2.1
 - Realme 8 pro

Its not my wifi my download mbps is 80.9 and upload mbps is 130. Its the same on tv

**Comment by Salamanka1212** [comment]
https://drive.google.com/file/d/1Bc6tnFRnUfX9F_h_F3lHAHC2efXCg1Oy/view?usp=drivesdk

**Comment by Benhirer** [comment]
> https://drive.google.com/file/d/1Bc6tnFRnUfX9F_h_F3lHAHC2efXCg1Oy/view?usp=drivesdk


> Idk if this is a bug but when I try to watch its not loading properly, maybe its gogoanime problem
> 
> Steps to reproduce the behavior:
> 
> 1. Go to any video
> 2. Click on any links from 1080 to 720
> 3. See error
> 
> * Android 11
> * 1.2.1
> * Realme 8 pro
> 
> Its not my wifi my download mbps is 80.9 and upload mbps is 130. Its the same on tv

😊 you can try changing time when it stops. I think it will works, so try it.

**Comment by Benhirer** [comment]
> > https://drive.google.com/file/d/1Bc6tnFRnUfX9F_h_F3lHAHC2efXCg1Oy/view?usp=drivesdk
> 
> > Idk if this is a bug but when I try to watch its not loading properly, maybe its gogoanime problem
> > Steps to reproduce the behavior:
> > 
> > 1. Go to any video
> > 2. Click on any links from 1080 to 720
> > 3. See error
> > 
> > 
> > * Android 11
> > * 1.2.1
> > * Realme 8 pro
> > 
> > Its not my wifi my download mbps is 80.9 and upload mbps is 130. Its the same on tv
> 
> 😊 you can try changing time by swipe to seek few sec forward or you can restart you device. I think it will works, so try it.

**Comment by deceptions** [comment]
As mentioned in https://github.com/deceptions/no/issues/4 gogo switched to slower servers and there is nothing I can do.
