### ISSUE TITLE
All these sources are so crappy , add some better asap

### ISSUE THREAD

**Issue by Adi-MayNotSpeak** [deceptions/no#92]
I can't even watch naruto in more than 360p , I will be switching to cloudstream for a while until you add a better resource , please do it fast because I love this app 🥺🥺

**Comment by Redddtt** [comment]
pretty sure thats not gonna pressure the devs for adding more sites, stop bragging about it naturally Naruto has crappy quality its even crappier on gogoanime since they stretched it out.

**Comment by Redddtt** [comment]
Ps: 1080p source on gogoanime is working fine in the app

**Comment by Adi-MayNotSpeak** [comment]
> pretty sure thats not gonna pressure the devs for adding more sites, stop bragging about it naturally Naruto has crappy quality its even crappier on gogoanime since they stretched it out.

I am talking about shippuden , gogoanime doesn't even appear as a source in shippuden 

P.S. see episode 79 and 81 , there are many many others too

**Comment by deceptions** [comment]
New site is already planned.

**Comment by Adi-MayNotSpeak** [comment]
> New site is already planned.

Oh i see, is it tenshi.moe ?
