### ISSUE TITLE
Removing an anime on continue watching _ Red.

### ISSUE THREAD

**Issue by Redddtt** [deceptions/no#94]
U need to restart the app to see that an anime is removed., removing an anime on continue watching then going to other pages then going back makes the removed anime reappear even tho it's removed when the app is restarted

1. Remove an anime on continue watching
2. Click on an anime page, library etc
3. Go back to the home page

https://drive.google.com/file/d/1RvEOtPhVIl0NHE6Ac74QtkZm2xMFZKKF/view?usp=drivesdk

 - Android 11
 - 1.8.4
 -

**Comment by deceptions** [comment]
Fixed next update.
