### ISSUE TITLE
2 Vidstream sources for SOME anime

### ISSUE THREAD

**Issue by Redddtt** [deceptions/no#95]
There are two Vidstream sources available for SOME animes ( like Sekai Saikou no Ansatsusha, Isekai Kizoku ni Tensei suru (Dub)ep 1,Renjian Zui Deyi ep1)

https://drive.google.com/file/d/1RxLakNuTm5wmpkH3LyaDKZ1xU9PhE5KK/view?usp=drivesdk

 - Android 11
 - 1.8.4
 - Phone

Hopefully this isnt an internet issue cuz someone said it, Fyi-Already tried the basics on fixing vid sources still the same

**Comment by deceptions** [comment]
The scraper is catching the backup source too, a recent addition to their sources. Will be labeled correctly in the next update.
