### ISSUE TITLE
subscription bug

### ISSUE THREAD

**Issue by ghost** [deceptions/no#96]
I added aot s4 and one piece in subscription under 2hrs interval but I didn't get any notification for new episode as the shiro app was giving.

1.8.4 
Android 10
Redmi note 7

**Comment by deceptions** [comment]
Different subscription model. Shiro was instant as the server sent out the push notifications, not possible as a scraper. The subscription fetches the anime in the background every ~2 hours (which may be longer or never if the app is killed) and compares with what it last fetched. This makes aggressive battery killing (common in Xiaomi) break subscriptions as it kills the background process necessary to make subscriptions work. Look at https://dontkillmyapp.com/.

Another possibility is that you simply opened the anime manually before the check, updating the notification to trigger on the next unreleased episode.

Either way it is not getting fixed app wise as frankly I do not know how to and it works on my device.
